### ISSUE TITLE
Manifest error

### ISSUE THREAD

**Issue by chrisemsen** [wwwXpert/chrome-ext-jira-notifications-off#1]
Just tried to install and getting an error when I drop the folder into Chrome ... 
"Manifest version 2 is deprecated, and support will be removed in 2023"

Can you update please?

I tried just changing the number to 3, but still allows the popups - but they have no text nor a close button :(

**Comment by wwwXpert** [comment]
@chrisemsen I simply changed the manifest.json file entry for manifest_version to 3. It should work.
